- packages/parser/__tests__/angular.spec.ts
- packages/parser/__tests__/fixtures/angular/src/app/foo/foo-routing.module.ts
- packages/parser/__tests__/parser.spec.ts
- packages/parser/src/angular/index.ts
Fix #44 
The issue was caused by not recursively traversing the child lazy routes. Basically, the route was pointing to `foo.module.ts#FooModule` which imports `foo-routing.module.ts#FooRoutingModule`. In the map, we had an entry for `foo-routing.module.ts#FooRoutingModule` but we didn't have one for `foo.module.ts#FooModule`. Now, both keys point to `foo-routing.module.ts#FooModule`.
> Collect nested routes in lazy modules

- packages/webpack/README.md
- packages/webpack/src/guess.ts
This PR allows us to specify custom report provider. This way, for code-labs we can share an already available report in the form of a file.
> Allow custom report provider

- config.json
- infra/build.ts
- packages/ga/src/ga.ts
- packages/ga/webpack.config.js
- packages/parser/webpack.config.js
- packages/webpack/package.json
- packages/webpack/src/api.ts
- packages/webpack/src/ga-provider.ts
- packages/webpack/src/guess-webpack.ts
- packages/webpack/src/prefetch-plugin.ts
- packages/webpack/src/runtime/guess.tpl
- packages/webpack/src/runtime/guess.ts
- packages/webpack/src/runtime/runtime.tpl
- packages/webpack/test/fixtures/delegate/webpack.config.js
- packages/webpack/test/fixtures/prefetch/webpack.config.js
- packages/webpack/webpack.config.js
This PR introduces:
- Allows GA authentication with a file, to let us build in CI (cc @KyleAMathews)
- Increases the GA result page size, so we don't hit the API limit too fast
- Build improvements which let us run `guess({ ... })` during SSR
- Version bump 🎉
> Credentials file authentication & build fixes

- packages/guess-webpack/src/ga-provider.ts
Currently it is backwards and causes the error:
`Error: Invalid Date Range: end-date 2017-07-30 precedes start-date 2018-07-30`
> Fix default time period

- packages/guess-parser/package-lock.json
- packages/guess-parser/package.json
- packages/guess-parser/src/angular/index.ts
- packages/guess-parser/src/preact/index.ts
- packages/guess-parser/src/react/base.ts
- packages/guess-webpack/test/fixtures/delegate/package-lock.json
- packages/guess-webpack/test/fixtures/prefetch/package-lock.json
`ngast@0.2.0` introduces support for Angular v6 & v7.
Closes #79
> chore: update ngast with support for Angular v7

- packages/guess-parser/package.json
**What**:
`typescript` is added as a peer dependency. I've picked `~2.7.2` because it's the most restrictive request from your dependencies (via `ngast`).
**Why**:
`@angular/cli` and `ngast` both have a peer dependency on `typescript`, but this package doesn't provide it - which is [invalid](https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0).
> Adds typescript as a peer dependency of guess-parser

- packages/guess-ga/src/client.ts
I've discovered a bug while implementing this on https://www.gatsbyjs.org. It seems like there is an infinite loop while fetching ga data when any page besides the first does not have a nextPage property.
I was trying to create some tests for it but the current jest setup does not allow it as packages are not hoisted.
example:
first request returns:
```json
{
"columnHeader": {
},
"data": {
},
"nextPageToken": "10000"
}
```
next request returns:
```json
{
"columnHeader": {
},
"data": {
},
}
```
it will keep on looping with pageToken "10000"
> fix(guess-ga): fix infinite loop on nextPage

- packages/guess-webpack/src/runtime/guess.ts
startWith is not in the es2015 spec which means IE11 breaks here. [IE11 supports prefetch](https://caniuse.com/#search=prefetch) which is why in my opinion runtime should be compatible with IE11.
The problem lies with typescript nor babel transpiles or polyfill the `startWith` function. This replaces `startWith` with `[0]` as we only check the first character.
If you feel like we should polyfill this instead of changing guess itself, feel free to close this one.
> fix(guess-webpack): runtime compatibility es2015

- packages/guess-ga/webpack.config.js
- packages/guess-parser/webpack.config.js
- packages/guess-webpack/webpack.config.js
when trying to build guess-webpack, .ts files were used as externals which broke the bundle when using it. On windows, file path requests are using `c:\` or `d:\` which fit the `\w` regex. On Linux/mac we start with a `/`. Now I check if a package starts with `@` and do not start with `c:\` it's an external package.
To test:
regex: `/^(@|\w{3}(?<!\w:\\)).*$/igm`
```
@test
jquery
mypackage
c:\
```
> chore: rework externals regex in webpack to support windows

- packages/guess-parser/src/angular/index.ts
I noticed a little regression in the latest version (v.0.3.10) of guess-parser. Previously it was possible to parse an Angular app which did not contain any routes. When calling `parseAngularRoutes(pathToTsConfig)` it did just return an empty array. But the newest version of guess-parser throws an error instead.
I added a simple check to restore the old behavior. However I don't know if this was the most clever thing I could do. Please let me know if there is a better way of doing it.
I would also be happy to add a test for that edge case if you think it is necessary.
> [guess-parser] handle Angular apps without any routes

- infra/e2e.ts
- packages/guess-webpack/src/aot/aot.tpl
- packages/guess-webpack/src/aot/guess-aot.ts
- packages/guess-webpack/src/declarations.ts
- packages/guess-webpack/src/guess-webpack.ts
- packages/guess-webpack/src/prefetch-aot-plugin.ts
- packages/guess-webpack/test/fixtures/angular/webpack.extra.js
This should shrink bundles with lots of instructions. It also introduces a breaking config change:
```ts
{
runtime: {
basePath: '...'
}
}
```
is now:
```ts
{
runtime: {
base: '...'
}
}
```
> Do not include base path in each instruction

- packages/guess-parser/src/angular/index.ts
Not the most beautiful fix and we should dig deeper in it but it works.
- readChildren returns already nodes on some typescript versions
> fix(guess-parser-angular): readChildren

- packages/guess-parser/src/angular/index.ts
- packages/guess-parser/test/angular.spec.ts
- packages/guess-parser/test/fixtures/angular/library/index.ts
- packages/guess-parser/test/fixtures/angular/library/library.module.ts
- packages/guess-parser/test/fixtures/angular/library/tsconfig.json
- packages/guess-parser/test/fixtures/angular/src/app/app-routing.module.ts
- packages/guess-parser/test/fixtures/angular/src/app/wrapper/wrapper.module.ts
- packages/guess-parser/test/fixtures/angular/src/tsconfig.spec.json
- packages/guess-parser/test/fixtures/angular/tsconfig.json
- packages/guess-parser/test/parser.spec.ts
This pull request will add support for parsing Angular applications developed with [nrwl/nx](https://github.com/nrwl/nx). Typically those applications use barrel files and set the paths property  in the tsconfig files to rewrite imports.
The first commit is meant to handle barrel files. It makes sure that `export * from './foo.ts';` counts as an import statement. I found the info that `exportClause` will be undefined for those exports in the TypeScript source code: https://github.com/microsoft/TypeScript/blob/master/src/compiler/types.ts#L2459
The second commit makes sure that `resolveModuleName` from TypeScript is used to resolve the full path of each import. This will resolve imports which refer to a local project like `import { AnyModule } from '@mylocalproject/library';`.
I have not …
> [guess-parser] handle nx-style monorepos

- packages/guess-parser/src/angular/index.ts
- packages/guess-parser/test/fixtures/angular/library/index.ts
- packages/guess-parser/test/fixtures/angular/library/nested/library.module.ts
Unfortunately I made a mistake in my last pull request. `resolveModuleName()` was called with the `child` instead of the `parent`. This wasn't noticeable with the previous fixture. But it surfaces when we nest the library module in yet another folder. I updated the fixture to reflect that.
Please let me know if there is anything I need to change.
> [guess-parser] Fix module resolution of nested modules

- packages/guess-parser/src/angular/index.ts
This pull request is intended to fix a problem with inconsistent file paths. As it turns out TypeScript always uses slashes ("/") in file paths no matter which operating system is used. But the rest of the code is using the separator of the operating system. This becomes a problem when two paths need to be compared.
I found the information that TypeScript always uses slashes in the source code of TypeScript itself: https://github.com/microsoft/TypeScript/blob/master/src/compiler/path.ts#L4. "Internally, we represent paths as strings with '/' as the directory separator."
These changes are also intended to fix chrisguttandin/angular-prerender#88.
> Normalize paths provided by TypeScript

- packages/guess-parser/package.json
If a specific pinned version is required it is better off as a direct dependency.
> fix: change typescript peer dependency to a loose patch

- packages/guess-ga/README.md
Per request in #328, I have updated the documentation to both include setup instructions, and creating a JWT client instead of just using a key.
Most of this has been shamelessly grabbed from parts of [experiments/guess-static-sites/README.md](experiments/guess-static-sites/README.md) with very few adjustments (using JSON credentials over P12 key)
Any input welcome
> Improve `guess-ga` setup documentation

- experiments/guess-static-sites/package.json
Fix filename for generate-prediction-tests script in package.json in guess-static-sites experiment.
> Fix filename for generate-prediction-tests script in package.json

- packages/guess-parser/src/angular/index.ts
Windows uses the `'\'` in its file names. I ran into a couple places where this wasn't taken into account.
1) Parsing routes in my angular app on my windows machine would fail when matching the TypeScript resolved modules file name to the OS file name (like `line 337`). 
I fixed this by normalizing the resolved file name using the `normalizeFilePath` method which was the process utilized by the `imports()` method above.
2) On line 236-9, I didn't know if the `split('/') ... join('/')` should use `path.sep` instead of '/'. My use case never falls through to this code and I didn't want to assume so I left it alone.
3) Mapping the excluded files to an absolute path was broken on windows because an absolute path on windows starts with the directory (eg `c:\` or `d:\`) not a `/` like linux …
> Adds windows file path format support when parsing routes

- packages/guess-parser/src/angular/index.ts
- packages/guess-parser/test/angular.spec.ts
- packages/guess-parser/test/fixtures/angular/src/app/app-routing.module.ts
- packages/guess-parser/test/fixtures/angular/src/app/lazy/lazy-routing.module.ts
- packages/guess-parser/test/fixtures/angular/src/app/lazy/lazy.component.ts
- packages/guess-parser/test/fixtures/angular/src/app/lazy/lazy.module.ts
- packages/guess-parser/test/parser.spec.ts
The changes introduced by this pull request aim to fix a bug which was originally reported for angular-prerender (chrisguttandin/angular-prerender#112). It might also fix #315 and #336 as the reports look fairly similar.
The problem was that guess-parser did not look recursively for entry points so far. Therefore I introduced the `collectEntryPoints()` function which keeps on looking for entry points as long as there are children in the currently handled route definition.
I also removed a part of the `readChildren()` function as it was returning wrong results. Apparently removing  the `evaluate()` call did resolve the issue. Please let me know if there is a better way to fix this.
> fix: handle lazy loaded routes which are children of eager routes

- README.md
In the webstandards section a new line was missed before starting the numbered lines.
> Update readme for missed new line
